<?php

namespace Msite\MsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppExamMappingRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AppExamMappingRepository extends EntityRepository
{
}
